In [28]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
from sklearn import linear_model

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [29]:
df = pd.read_csv("hiring.csv")

In [30]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

# Data Preprocessing 

## Handle Null Values

In [31]:
pip install word2number

Note: you may need to restart the kernel to use updated packages.


In [32]:
from word2number import w2n

In [33]:
def safe_word_to_num(val):
    try:
        return w2n.word_to_num(str(val))
    except:
        return None

df['experience'] = df['experience'].apply(safe_word_to_num)

In [34]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         NaN                    8.0                           9      50000
1         NaN                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [35]:
median_experience = df.experience.median()

In [36]:
df['experience'] = df['experience'].fillna(median_experience)

In [37]:
df

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0         6.0                    8.0                           9      50000
1         6.0                    8.0                           6      45000
2         5.0                    6.0                           7      60000
3         2.0                   10.0                          10      65000
4         7.0                    9.0                           6      70000
5         3.0                    7.0                          10      62000
6        10.0                    NaN                           7      72000
7        11.0                    7.0                           8      80000

In [38]:
df = df.rename(columns={'experience':'experience', 'test_score(out of 10)':'test_score(out_of_10)','interview_score(out of 10)':'interview_score(out_of_10)','salary($)':'salary'})
df

experience  test_score(out_of_10)  interview_score(out_of_10)  salary
0         6.0                    8.0                           9   50000
1         6.0                    8.0                           6   45000
2         5.0                    6.0                           7   60000
3         2.0                   10.0                          10   65000
4         7.0                    9.0                           6   70000
5         3.0                    7.0                          10   62000
6        10.0                    NaN                           7   72000
7        11.0                    7.0                           8   80000

In [39]:
mean_test_score = round(df['test_score(out_of_10)'].mean())
mean_test_score

8

In [40]:
df['test_score(out_of_10)'] = df['test_score(out_of_10)'].fillna(mean_test_score)

In [41]:
df

experience  test_score(out_of_10)  interview_score(out_of_10)  salary
0         6.0                    8.0                           9   50000
1         6.0                    8.0                           6   45000
2         5.0                    6.0                           7   60000
3         2.0                   10.0                          10   65000
4         7.0                    9.0                           6   70000
5         3.0                    7.0                          10   62000
6        10.0                    8.0                           7   72000
7        11.0                    7.0                           8   80000

# Create the model

In [42]:
model = linear_model.LinearRegression()
model.fit(df[['experience','test_score(out_of_10)','interview_score(out_of_10)']],df.salary)

LinearRegression()

In [43]:
model.predict([[9,6,10]])

array([74455.28455285])

In [44]:
model.coef_

array([2813.00813008, 1333.33333333, 2926.82926829])

In [45]:
model.intercept_

11869.91869918695

In [46]:
import joblib

In [47]:
joblib.dump(model , 'model_joblib')

['model_joblib']

In [48]:
mj = joblib.load('model_joblib')

In [49]:
mj.predict([[9,6,10]])

array([74455.28455285])